import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">LandingPageDesktop</Link>
        </li>
        <li>
          <Link to="/aboutuspage">AboutUsPage</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/propertiespage">PropertiesPage</Link>
        </li>
        <li>
          <Link to="/prentapartmentpage">PRentApartmentPage</Link>
        </li>
        <li>
          <Link to="/ppaymentofrentalpage">PPaymentofrentalPage</Link>
        </li>
        <li>
          <Link to="/psecurepayment">PSecurePayment</Link>
        </li>
        <li>
          <Link to="/ptransferdetails">PTransferDetails</Link>
        </li>
        <li>
          <Link to="/pcongratulations">PCongratulations</Link>
        </li>
        <li>
          <Link to="/profilepage">ProfilePage</Link>
        </li>
        <li>
          <Link to="/ppaymentplanpage">PPaymentPlanPage</Link>
        </li>
        <li>
          <Link to="/contactuspage">ContactUsPage</Link>
        </li>
        <li>
          <Link to="/calculatorpage">CALCULATORPAGE</Link>
        </li>
        <li>
          <Link to="/registerpage">Registerpage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
